"""Init user model

Revision ID: 519cd620795f
Revises: 
Create Date: 2024-05-20 20:20:26.010520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519cd620795f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('password', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
